/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 25.04.2026 05:11:33

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 8
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 4256;
#else
constexpr int kTensorArenaSize = 3232;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,1000 } };
const TfArray<1, float> quant0_scale = { 1, { 0.031964626163244247, } };
const TfArray<1, int> quant0_zero = { 1, { 1 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 50, 20, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 50, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 25, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[4] = { 1, 25, 1, 32, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data5[2] = { -1, 416, };
const TfArray<1, int> tensor_dimension5 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data6[4] = { -110, -346, 462, 6, };
const TfArray<1, float> quant6_scale = { 1, { 0.00020300518372096121, } };
const TfArray<1, int> quant6_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data7[4*416] = { 
  -1, 3, 19, -7, 36, -23, -29, -29, 16, 23, -11, -13, -14, 37, -24, -31, 3, 3, -19, -22, -10, 3, -48, -2, 0, 11, -9, 19, -20, 15, 6, 6, -40, 22, 3, -6, 10, 7, 9, -25, 19, -2, 14, -30, 17, -4, 15, -1, 10, 16, 7, -21, -6, -6, -24, 9, -53, -21, -5, 1, 5, -11, 35, 16, -14, -25, -73, 20, -6, 13, 26, -14, -12, 36, -11, -50, -21, -19, 1, -27, -28, -59, 13, -22, 8, 4, -61, 6, 26, 63, 13, 38, 1, 11, 32, 11, -6, 8, -38, 26, -69, 12, 33, -55, -31, 61, -34, -44, 7, -38, 23, -7, -38, 2, -12, -54, 18, 30, -31, -22, 45, 47, -9, 3, -53, 10, 37, 1, -13, 21, -27, -35, -75, -23, 9, -6, 6, 55, 19, -30, 14, -34, 8, -36, -2, -49, 2, -20, -14, 38, -60, -7, 36, 26, 14, 12, -28, -8, 48, 33, -28, 1, 22, 25, -44, 6, 43, -30, -31, 30, 39, -13, -4, 20, 34, -31, -27, -74, -21, -21, -4, 3, 0, 23, 51, 26, -6, -24, -26, 47, 14, 18, 8, 0, -10, -47, -28, -27, -3, -14, -10, 11, -16, -102, -17, 18, 2, -42, -91, -71, 1, -1, 14, -1, 2, -21, 3, 3, -23, -18, -24, 5, 11, 0, 30, 11, -12, -39, -52, 13, 21, -43, -28, 30, -12, 30, -17, 34, -18, 7, -25, -33, 9, 34, -7, -16, -22, 32, 9, 29, -22, 29, -101, -8, 6, -13, 11, 2, 33, -19, 16, 9, 33, 18, -19, 39, 16, 66, 20, -20, -4, 9, -30, -37, 19, -2, 1, -7, 11, 20, 21, 22, 3, -51, -26, -24, 26, 13, -9, 22, -7, -52, -12, -10, 55, 13, -20, 42, -9, 10, -1, -127, -35, 5, -38, -49, 29, 37, -10, -19, -28, 41, 17, 3, 2, -72, -35, -18, -24, 18, 48, -1, 2, -26, 22, 18, 35, 35, -4, 26, 46, 33, 15, -36, -19, -2, -40, -33, 38, 50, -1, -25, -14, -1, -31, -17, -7, 14, 32, 14, 10, 32, 39, 11, 24, 3, 45, 15, 64, 32, 3, 31, 52, 47, -11, 10, -40, 25, -65, -80, 6, 83, -20, -30, -86, 36, -15, -67, -15, -9, 4, 10, -43, -1, -1, -3, 67, -7, 82, -31, 30, 64, 2, 46, 18, -1, -24, -27, -19, 58, -53, -26, -13, 77, -50, -36, 29, 59, -40, -15, -38, -15, 5, -44, -68, 39, 
  -7, 22, -55, -27, -20, -22, -67, 11, 1, -79, -17, 56, -19, 15, -48, -24, 0, -40, 4, -22, -44, -7, 24, -28, 74, 8, 5, 42, 42, -14, -18, -7, -1, 6, 1, -18, 16, -35, -71, -14, -13, -89, -5, 41, -23, 30, -47, -13, 3, -3, 22, 19, -30, -12, 38, -25, 56, 6, 55, 40, 3, -22, -30, 22, -3, 12, 33, 11, 12, -16, 2, -14, -14, -87, 19, 16, 1, 22, -41, -6, -16, -45, -13, 48, -38, -35, -4, 19, 37, -3, 4, 1, -16, -29, -41, -10, -3, 34, 34, -18, 39, -12, -16, 14, 7, -39, -10, -14, -51, -7, -17, -3, -13, -38, 11, 58, -26, -47, -5, -30, -3, 10, 41, 29, -1, -20, -58, -47, 10, 31, -5, -24, 59, -28, 26, 17, -5, -66, -10, 26, -36, -26, -18, -6, -34, -68, 44, 57, 9, 5, -81, 2, -41, -20, 9, 35, 48, -50, -9, -16, 35, -9, -13, -26, 12, -13, 41, 20, -5, -76, 1, 6, -51, 11, 17, -19, -30, -7, 14, 16, -20, 3, -38, -14, -39, -1, -1, 26, 16, 5, -64, -18, 28, -4, 10, -26, 16, -5, 15, 13, 14, -65, -31, 10, -22, -4, -13, 10, 30, 0, 22, 12, -34, -1, -31, -21, -32, 4, -13, -29, -11, -18, -9, -34, 11, -29, 6, -10, 10, -16, -1, 12, -6, -26, -12, -41, -13, -40, -5, 5, 17, 31, 11, 24, -32, 25, -15, -2, -66, -24, -19, -16, 25, -7, 18, -49, -17, -13, -21, -26, -19, -25, 2, -51, -13, -6, -75, 59, 10, 14, -5, -30, 23, 28, -2, 1, -32, 25, 3, -24, -20, -23, 8, 21, 39, -32, 25, -33, -18, 0, -1, -25, -80, -16, -40, -11, -38, -36, -64, 75, -23, 21, -29, 21, 17, 20, -1, -4, -50, 23, 10, -9, -62, -1, -14, 23, 18, 17, 18, -63, -18, -32, -14, 15, -50, 24, -46, -9, -14, -5, -49, 12, -25, 19, -18, -27, 11, 31, 0, -42, -20, 4, 5, 12, -10, -10, 31, 34, 9, -24, 12, -8, -31, -7, 5, -2, -58, -10, -45, -16, -16, 13, -87, -36, 21, 28, -25, -27, 48, 43, -6, -44, -39, 3, 33, 19, 35, -12, 15, 49, 0, 2, 30, -47, -39, 75, -10, -11, -126, 8, -54, -20, 14, 25, -35, 17, -32, -20, -3, -23, 33, 61, -11, -83, -28, 50, -49, -11, -58, 0, 62, 59, -25, 36, 38, -36, 
  -7, 15, 34, -48, -5, -22, 49, 40, 2, -13, 50, -16, 47, -30, 48, 57, 59, 32, -60, 60, 54, 4, 37, -17, -29, -19, -39, -46, -23, 21, 19, -1, -27, 34, 36, 25, 17, -31, 30, 51, 1, -7, -14, 16, 0, -27, -5, 13, 59, 40, -2, 5, 4, 19, -41, -17, 14, 14, -23, -67, -17, -12, -5, -20, 25, 47, 49, 13, 2, -4, 26, 20, -5, -15, 26, -6, 4, -14, 58, 21, 8, 13, -23, 23, -12, -4, 83, -26, -49, 3, 8, -32, -6, -46, 11, -78, 16, -64, 0, 26, -2, -17, -3, 36, 9, -63, -33, 17, -16, -9, -15, 33, 35, -31, -3, -24, 9, -30, 70, 24, -25, -41, -4, -68, 60, -30, 5, -9, 26, -1, 28, -30, -3, 30, 23, -16, 3, -61, -64, 23, -42, 36, 25, 37, 28, 36, -3, 7, 4, 21, 77, -7, 15, -7, 14, -29, 6, -50, -7, -34, -14, 8, 5, -4, 27, 19, -3, 47, 5, -25, -14, -49, 26, -69, 15, 21, 13, 1, -15, -50, 24, -25, 63, -6, -9, -3, 12, -49, 83, -28, -12, -36, -6, 2, -3, 3, -10, 10, 18, 19, 16, -67, -27, 51, -21, -25, 9, 1, 6, -33, -13, -45, 20, -20, -19, -23, -24, -24, -20, -46, 8, -35, -21, -35, -51, -11, 15, 14, 14, 11, -24, -5, -5, -66, 3, -8, 13, -11, 0, 23, -23, 23, 37, -32, 4, -3, 54, -22, -27, -32, -10, 8, 52, -54, -36, 10, 16, 42, -21, -6, 31, 7, -17, 7, 45, -91, -5, -19, -27, -17, -29, 8, -8, 2, -6, -16, 24, -1, 51, -19, -16, -33, 17, -24, 20, -9, -26, -2, -11, 27, 29, 11, 24, -28, -2, 8, 8, -26, -23, -53, -24, -40, 2, 57, -23, -28, -3, -35, 34, -13, 86, -11, -29, -48, 15, -29, 31, 15, -53, 4, 9, -32, 33, -5, 42, -27, 2, 49, 32, -30, 13, -39, -15, -45, 18, 9, -21, -30, -8, -7, 28, -23, 13, -21, -63, -32, -45, -55, 29, -6, 12, 10, 5, -5, 1, 22, 26, -22, 9, 43, 30, -76, 5, -30, -3, -52, 6, 37, -28, -22, -5, -2, 43, -46, 33, -20, 25, -9, -52, -21, 28, -26, -13, 40, -4, 27, -26, 39, 28, 15, -33, 26, -13, -52, 5, -34, 43, -72, -18, -36, -10, -21, -5, -9, 5, -5, 18, 14, 57, -5, -41, -88, 4, 16, -35, -19, 
  11, -11, -15, 37, 5, -12, 42, -18, -16, -23, -2, -3, -60, -23, 49, 26, -22, -62, -7, 7, 13, -29, -2, 11, -37, -27, 43, -17, -48, 22, -59, -40, 58, -45, -38, -25, -26, -7, -5, -15, -25, 19, -9, -11, 8, 6, 6, -21, -13, -52, 7, 12, 34, 0, -27, 7, -2, 18, -9, -37, -44, 33, -14, -7, -8, -37, 4, -31, -24, 14, -20, -3, -12, -5, 15, 27, -24, 14, -19, -35, 3, 57, -15, 3, 30, 18, -45, 14, 4, -12, -2, -36, -31, 9, -15, -26, -11, 11, 8, -33, -9, -16, -51, -11, 9, 22, 45, -8, 33, 48, 50, -3, 27, 10, -39, 9, 3, -11, -19, 5, -13, -26, 19, 23, 23, 7, -1, -4, 2, -24, 9, 43, 20, -4, -4, -16, 16, 47, 27, -9, 33, -1, 2, 29, 61, 15, -25, 26, -5, 25, 43, 18, -27, -14, -4, -38, -49, -5, -3, -8, -33, -12, 16, 2, 0, -15, -49, -9, -8, 33, -3, 22, 44, -42, 19, 11, 83, 71, 0, 14, 16, 44, -34, -8, -7, -23, -9, 43, 4, 26, 3, 16, -23, -14, 26, 8, 15, 21, -33, 1, 2, 41, 18, -2, 1, 21, -15, -6, 21, -4, -50, 13, -15, 28, -12, 44, 11, 36, -11, 2, -20, 48, -6, 19, -43, 38, -16, 37, 6, -17, -23, 25, 14, 38, 49, 2, -17, -22, -26, 11, 5, 4, -34, 12, 15, 16, -36, -5, -7, 24, 10, -3, 20, 35, 7, 13, 1, 12, -16, 15, -5, -5, -25, 27, -27, 30, 21, -61, 13, 33, -16, -26, 4, -5, 10, -3, 1, 20, -30, 42, -34, 34, 21, 6, 10, 14, 16, 22, -11, -23, -11, 6, -7, -16, -43, -15, 8, 13, 44, -26, 2, 73, 25, -53, 14, 14, -5, -7, -26, 20, -35, 30, 39, -3, 13, 50, 18, -5, 27, 53, -41, 6, -4, -24, -18, 8, -10, -29, -36, 19, -10, -57, -18, 40, -24, -18, 0, 1, 13, -20, -39, -16, -20, 18, 28, 41, 2, 31, -24, 10, -24, 3, -26, -1, -27, -13, -44, 4, -12, 20, 38, 1, -16, -46, -31, 22, -12, -35, 5, 27, -7, -49, -24, -6, -19, -19, -3, 40, -18, 14, -15, 33, 21, -21, 6, -35, -27, -1, -66, -15, -36, -26, -3, -22, -5, 27, 34, 41, 26, -22, 3, 1, -8, -63, 23, 23, 9, -46, -11, 6, 5, 31, -7, -14, 27, 7, 
};
const TfArray<2, int> tensor_dimension7 = { 2, { 4,416 } };
const TfArray<1, float> quant7_scale = { 1, { 0.0042237015441060066, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data8[32] = { 724, 59, 706, 17, 1153, -555, 508, 929, 184, -950, -241, -169, 860, 195, 1447, 1078, -366, -364, -328, -444, 1356, -753, 3267, -702, 504, -611, -611, -51, 1168, -173, -436, -217, };
const TfArray<1, int> tensor_dimension8 = { 1, { 32 } };
const TfArray<32, float> quant8_scale = { 32, { 8.159466233337298e-05, 7.2682225436437875e-05, 7.7260279795154929e-05, 8.4344326751306653e-05, 0.00011483205162221566, 6.5792635723482817e-05, 0.0001247374020749703, 8.4715262346435338e-05, 8.3468439697753638e-05, 8.5118568676989526e-05, 8.684798376634717e-05, 0.00010671732161426917, 7.7822849561925977e-05, 9.7330972494091839e-05, 9.7209500381723046e-05, 0.0001052049919962883, 9.3979091616347432e-05, 0.00011835685290861875, 8.6985135567374527e-05, 0.00010509802814340219, 8.7053784227464348e-05, 8.6340456618927419e-05, 9.7992902738042176e-05, 8.2398735685274005e-05, 9.6794690762180835e-05, 9.9266908364370465e-05, 7.3873612564057112e-05, 9.7189746156800538e-05, 0.00010691695933928713, 8.6931591795291752e-05, 8.2623657363001257e-05, 9.2755421064794064e-05, } };
const TfArray<32, int> quant8_zero = { 32, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[32*1*3*16] = { 
  /* [0][0][][] */ -11,54,-44,22,-45,-37,-67,39,52,-1,-101,58,42,88,83,-61, -68,-28,-127,85,-69,127,34,30,-45,-101,-115,22,111,-37,-90,-98, 70,18,-26,80,-13,-48,-50,81,121,-110,-9,37,59,-63,44,-62, 
  /* [1][0][][] */ -44,39,0,-63,-52,-92,127,25,2,37,-24,-52,36,39,-100,121, -17,86,-37,48,89,-38,-28,-53,-119,79,126,11,-33,21,8,43, -114,75,-9,-92,-26,41,-117,-40,-64,-110,-102,56,12,118,12,-78, 
  /* [2][0][][] */ 14,-59,-30,24,93,119,27,24,-88,36,-101,45,113,-42,-84,40, -6,17,68,-81,38,67,53,54,67,-70,-109,-67,-49,45,104,88, 40,18,-58,-48,90,-4,-44,112,-113,-105,32,5,-74,109,48,127, 
  /* [3][0][][] */ 65,91,28,-127,65,-32,-4,-30,-76,-72,73,73,41,61,-41,-102, 23,-32,-57,-50,-44,62,-83,106,87,41,32,54,-106,-1,-61,-58, -74,97,77,8,-3,-26,77,-118,74,49,-49,-20,-89,56,-107,33, 
  /* [4][0][][] */ -24,7,-76,22,-55,15,58,63,44,-26,-70,74,-40,48,25,80, -18,51,-72,-49,29,45,92,127,-57,-72,-19,62,-86,35,-2,50, -42,-45,47,-69,-78,27,68,56,-48,13,26,83,17,86,-37,-50, 
  /* [5][0][][] */ -100,59,-27,-75,-67,-50,63,-100,-77,36,0,-92,-45,-13,23,-77, -105,-9,63,57,41,-15,-115,5,7,-100,-87,-44,3,-68,-4,9, 12,-29,-20,-90,-9,-58,64,-50,-114,-60,-42,95,3,-65,-127,-65, 
  /* [6][0][][] */ 20,-22,-127,24,-5,92,-58,42,-58,-83,-52,-5,-59,49,-26,-44, 39,-71,11,20,-5,80,-10,98,56,-15,-83,-27,52,-21,56,-67, -62,16,-49,21,11,-9,-57,0,24,-64,-111,-30,-48,65,23,-19, 
  /* [7][0][][] */ -52,25,-108,40,27,100,40,89,27,-104,58,82,-40,37,95,36, 26,65,-75,38,-41,-17,-37,11,-76,3,-44,-40,-84,34,48,-49, -3,14,-29,79,29,-110,41,-37,40,-2,-79,127,20,88,-83,73, 
  /* [8][0][][] */ 65,127,-9,-2,-4,-52,65,-58,-2,57,10,-34,-2,53,12,23, 44,95,9,-117,-45,-54,32,75,48,25,58,73,25,68,48,-71, 105,-50,-10,24,-42,9,-8,-11,-90,-107,-93,120,-42,15,-13,-59, 
  /* [9][0][][] */ -24,22,13,106,-27,29,-11,-13,-11,-75,55,-67,-112,-60,-72,22, -72,91,67,52,-10,125,-48,54,-93,-27,97,-61,-59,-12,-115,-59, -15,-50,104,24,54,107,-63,-42,-127,-67,57,-74,-122,-35,12,83, 
  /* [10][0][][] */ -90,-14,22,76,-40,-5,-28,-90,-98,-93,17,-45,-18,7,-36,60, 70,96,-26,95,74,2,15,-28,-16,-94,49,34,-124,127,23,-38, -78,-76,-20,81,-21,6,31,124,-38,-93,-11,55,-105,94,-92,86, 
  /* [11][0][][] */ -71,-59,91,-22,-26,61,87,31,-11,-66,-71,-107,76,6,2,-14, -50,-127,10,13,13,59,-78,22,-109,41,-17,-90,60,33,-83,-114, -61,2,-82,96,61,67,37,43,-106,-67,9,-58,-7,-23,-35,63, 
  /* [12][0][][] */ -79,-56,-89,78,63,-79,-102,-106,57,21,65,-66,-127,-64,5,38, 56,17,20,36,10,124,-9,-12,-51,-54,28,-98,-81,46,15,31, 49,87,76,13,81,11,-10,97,-95,-68,54,15,66,33,-122,8, 
  /* [13][0][][] */ 32,-60,-104,-31,40,-27,-127,-45,3,116,-6,-115,26,-65,76,50, 52,-122,-90,100,-39,79,-18,8,-6,-8,-111,-101,45,-23,77,-67, -24,-70,4,1,74,-8,-61,-23,25,92,-14,7,31,-84,16,70, 
  /* [14][0][][] */ 73,68,-6,-30,12,16,-9,60,111,43,12,57,47,-32,-46,17, 111,18,50,72,-27,-44,-38,-127,-9,-7,-21,-61,-91,-7,94,18, -9,-38,-16,-17,-34,-68,35,-39,48,-73,-12,-62,-87,65,30,18, 
  /* [15][0][][] */ 53,-35,-20,-50,-16,57,28,20,-45,9,-106,-20,25,13,-7,-27, -38,55,-51,29,33,58,59,-18,0,-66,-55,28,7,65,21,14, 54,70,-127,-51,-51,-11,34,107,60,-57,39,40,-110,66,24,63, 
  /* [16][0][][] */ 105,111,37,-18,89,-19,48,-41,66,-60,-10,64,1,36,-78,-103, 20,38,41,-127,124,-14,100,-40,23,-65,77,19,-19,-46,-28,-93, 64,34,-35,-83,30,-98,-33,41,-40,-12,61,104,-36,-44,-61,-70, 
  /* [17][0][][] */ 78,70,-25,-11,50,-33,120,53,41,-117,-22,-2,17,-45,-77,-56, 75,35,27,-80,45,-68,69,-26,-36,-102,59,-21,-10,-13,-8,-51, -46,28,-12,-127,77,-38,-28,22,-2,-23,85,-22,-26,5,-38,3, 
  /* [18][0][][] */ -17,-46,-50,46,-53,66,-127,108,16,-58,-38,54,60,3,40,41, 43,-64,-22,-61,-112,2,-7,-28,-16,50,24,22,86,90,-18,27, -78,-17,-83,-32,-63,-35,32,40,36,-9,-75,26,-8,66,-102,-55, 
  /* [19][0][][] */ -58,-72,21,55,-60,127,-16,74,-23,-39,-20,79,-45,12,-34,1, -28,-58,35,69,15,92,-57,79,41,-105,-27,27,-32,-28,-34,13, -58,-79,-53,26,36,41,-83,45,-49,-99,18,88,-50,48,62,-56, 
  /* [20][0][][] */ -44,-36,-62,7,-58,-65,64,-25,116,-62,91,9,-47,51,84,-43, 99,-1,83,23,-24,23,6,-23,-4,-4,-62,-127,-12,40,-12,58, 53,-27,-40,73,-54,-86,72,10,99,-74,-51,-10,-56,35,-21,-4, 
  /* [21][0][][] */ 23,79,-46,96,61,-57,72,-46,86,-22,57,58,19,-44,-50,-111, 13,30,62,53,99,14,34,-49,12,7,75,-24,-21,20,-127,-83, -25,69,54,-54,91,-78,28,-30,-35,70,34,40,20,-30,-121,-80, 
  /* [22][0][][] */ 14,75,-107,-12,-111,-84,0,30,-1,30,-3,-80,-17,41,47,10, 4,-44,24,-8,70,-40,49,94,-6,-98,-5,-52,-38,-12,102,127, 12,127,-64,-40,-46,-52,-56,56,-71,71,-28,-49,-88,102,25,49, 
  /* [23][0][][] */ 29,-127,119,70,34,102,19,57,-69,-83,-12,1,44,-92,-97,29, -28,37,54,55,-44,6,-67,112,-113,-49,-29,80,-86,37,-24,55, -49,-11,19,67,-2,-34,41,33,-63,-83,94,-83,15,-116,-55,-57, 
  /* [24][0][][] */ -98,19,0,26,-70,-54,-19,28,-70,92,65,-17,-58,0,-64,-23, -12,-56,75,45,-99,26,64,-50,-127,42,95,11,-25,-43,-112,63, -52,16,-63,-79,-88,-57,28,-119,-61,105,92,-40,74,63,-85,47, 
  /* [25][0][][] */ -102,38,97,18,-42,-88,33,-30,-103,72,62,69,29,-64,21,29, -104,-70,31,-54,-3,-29,43,-80,26,19,31,7,-26,-15,-41,54, 4,26,83,-17,1,-127,-9,-56,-67,31,11,66,-58,-49,-38,-43, 
  /* [26][0][][] */ -47,8,-54,-4,-122,-44,-119,19,-59,82,12,113,31,42,40,81, -87,-64,-84,62,42,-17,2,-76,-87,90,-107,-35,70,14,42,-12, -46,-21,-63,-115,-40,-50,56,-127,54,-57,11,-99,-8,-16,-41,27, 
  /* [27][0][][] */ 8,63,17,-62,-56,28,-52,8,-46,98,-68,14,95,-64,-41,-60, 6,15,-22,-50,-93,-22,-21,-80,-119,127,-32,-15,67,40,4,-19, -80,38,23,64,-79,41,43,-61,-99,42,-57,-7,33,34,1,18, 
  /* [28][0][][] */ 37,112,-26,-35,4,-31,71,5,32,-2,-43,73,-85,15,26,71, 41,20,-32,-12,26,-20,-28,51,-127,-51,-13,46,-18,67,-19,-65, -11,-15,-46,7,-6,-59,44,19,-69,77,-15,-27,53,59,-66,86, 
  /* [29][0][][] */ -62,-72,45,4,-13,-18,-83,-90,29,18,-58,36,-26,-103,-60,12, -10,-115,65,119,-127,-79,-28,2,33,66,-12,-66,5,-54,-31,-1, 54,-13,-7,62,32,13,19,-27,125,-16,-18,-52,-77,-86,59,36, 
  /* [30][0][][] */ 22,-8,99,-85,113,-62,-12,-94,-45,90,-32,-24,-97,-108,70,-50, 79,61,46,13,91,-112,-14,-31,27,-13,127,-66,-78,-82,-73,-4, 47,-87,83,50,99,-39,-50,-116,-64,-1,52,-74,-14,-18,-76,79, 
  /* [31][0][][] */ 1,-51,-14,52,-36,-41,-31,4,-85,-40,2,27,-41,-54,18,13, -99,23,104,89,-19,-54,50,-77,-45,-67,-55,63,-24,67,-62,-8, -38,-44,33,96,2,-71,22,-3,-127,71,30,8,-13,91,-9,92, 
};
const TfArray<4, int> tensor_dimension9 = { 4, { 32,1,3,16 } };
const TfArray<32, float> quant9_scale = { 32, { 0.0023334508296102285, 0.0020785720553249121, 0.0022094957530498505, 0.0024120858870446682, 0.0032839763443917036, 0.0018815431976690888, 0.0035672504454851151, 0.0024226938840001822, 0.0023870372679084539, 0.0024342276155948639, 0.0024836857337504625, 0.0030519105494022369, 0.0022255841176956892, 0.0027834789361804724, 0.0027800051029771566, 0.0030086608603596687, 0.0026876216288655996, 0.0033847787417471409, 0.0024876079987734556, 0.0030056019313633442, 0.002489571226760745, 0.002469171304255724, 0.0028024089988321066, 0.002356445649638772, 0.002768142381682992, 0.0028388430364429951, 0.0021126435603946447, 0.0027794402558356524, 0.0030576197896152735, 0.0024860766716301441, 0.0023628780618309975, 0.0026526269502937794, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[16] = { 1665, 1213, -1554, -752, -1222, -585, 571, 1566, 1551, 0, -2361, -107, -1522, 1972, 2547, 1423, };
const TfArray<1, int> tensor_dimension10 = { 1, { 16 } };
const TfArray<16, float> quant10_scale = { 16, { 9.0240202553104609e-05, 0.00012652580335270613, 0.00012012004299322143, 0.00010996252240147442, 9.1534355306066573e-05, 0.00011576854012673721, 0.00010411778202978894, 0.00012572167906910181, 0.00011771194112952799, 0.0001288737403228879, 0.000101955454738345, 9.1012589109595865e-05, 9.1810004960279912e-05, 0.00010152362665394321, 9.745320858201012e-05, 0.00010416342411190271, } };
const TfArray<16, int> quant10_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[16*1*3*20] = { 
  /* [0][0][][] */ 0,37,-124,82,-22,-11,85,-110,-53,-16,19,44,49,-3,19,-122,-25,40,-2,93, 81,-29,-41,96,-13,23,-69,17,26,-32,-90,21,-17,27,13,-15,-49,51,6,-85, 99,98,59,-60,-58,15,70,-86,-101,54,49,11,-3,-56,-33,-127,29,-11,-56,101, 
  /* [1][0][][] */ -67,-19,-127,-46,-21,-64,97,62,-42,56,4,-2,27,-81,-13,30,-32,-28,-64,8, 70,-34,-40,65,22,-7,51,-70,-21,-30,15,-31,-31,15,-37,-14,-6,5,-16,-13, 60,17,-64,96,-51,-56,88,1,-42,44,-32,-57,5,-3,-76,35,23,-23,19,-20, 
  /* [2][0][][] */ 70,-14,-72,65,-4,5,24,-15,-30,45,99,-9,-9,4,5,-14,-50,30,9,-23, 74,27,-40,41,67,38,-3,53,-100,83,62,-42,19,-15,-22,-8,-17,-51,-60,-48, 65,-26,7,75,75,-41,12,47,-127,99,69,-73,83,32,33,59,28,5,-22,-45, 
  /* [3][0][][] */ 11,-20,27,80,69,39,-41,49,72,53,54,10,20,74,127,107,63,1,-28,-44, 7,-10,35,40,60,-5,-75,83,111,35,63,-46,16,77,89,120,43,-61,3,24, 93,34,8,19,-60,31,-73,-54,0,-2,-8,-72,9,38,88,107,37,-65,10,-62, 
  /* [4][0][][] */ 80,46,-127,-1,-23,-43,53,-99,-38,-30,5,-108,-86,-50,60,-71,-26,69,-43,-21, 73,108,-98,79,10,3,11,-98,-68,31,60,18,-51,-9,-40,-88,-73,71,-53,-71, 88,-29,-109,65,13,-44,83,-120,-108,-9,36,12,-18,-57,-22,45,38,-89,75,16, 
  /* [5][0][][] */ 8,16,23,-103,29,-55,6,-22,-48,31,-73,16,-21,-28,-39,-62,25,64,85,79, -7,35,15,-117,-9,-24,-9,-45,2,28,39,5,-52,-105,36,-34,-13,16,47,1, 81,53,-21,-55,23,53,-49,-93,120,-47,85,-127,-14,12,53,19,-24,1,75,40, 
  /* [6][0][][] */ 58,35,-55,-39,-36,-38,0,-37,12,-7,-2,-27,-15,40,-13,-24,15,-16,-100,-27, -25,108,-92,52,19,-48,19,56,-36,73,-18,-58,-19,-55,-46,39,-30,-68,50,-64, -23,-17,-127,33,103,-25,91,-68,25,4,-22,-55,48,-63,-17,-88,-46,25,-100,-98, 
  /* [7][0][][] */ 55,41,30,-127,4,9,15,10,-26,-75,26,-85,71,-51,79,-19,40,1,56,62, 12,-55,-69,-58,50,0,48,-56,-4,20,17,18,1,-62,67,-32,19,42,79,-6, 23,-34,-33,-61,64,-47,-69,9,71,14,-24,-3,-71,-17,6,53,-51,-34,-24,18, 
  /* [8][0][][] */ 28,-26,-32,5,-7,-40,-80,57,65,-96,44,39,-45,-61,-127,-4,-42,-18,-30,90, 15,33,-60,61,-17,38,59,34,48,-9,19,-8,-18,30,-67,3,-68,6,19,18, -22,-64,-90,-14,71,-92,-63,-29,-51,-45,-57,23,-99,37,-70,-107,-43,26,61,51, 
  /* [9][0][][] */ -72,23,80,94,-34,-8,-97,52,-38,94,-60,37,-33,-29,-9,-65,-12,-3,-62,-40, -18,-22,66,93,-24,10,-96,80,-127,-13,32,31,10,-24,37,-22,51,-26,-24,-72, -62,-40,73,35,-19,54,-36,36,36,-35,32,95,78,109,-5,-25,-69,65,-61,-27, 
  /* [10][0][][] */ 121,41,-115,41,37,-127,16,56,-79,71,84,57,7,-61,-17,12,65,-32,-91,-17, 38,29,-51,-12,-11,-96,101,36,-85,62,88,30,61,6,-10,69,9,-10,5,-61, 2,41,-81,84,-25,-44,118,54,-92,2,46,38,14,4,16,18,-26,-33,30,-53, 
  /* [11][0][][] */ 0,-91,-78,-40,-38,-95,114,-8,-25,-35,37,70,57,-127,-21,52,33,3,27,103, -42,-45,-9,-87,93,-38,-10,-88,39,18,36,35,10,-50,-17,121,-61,-65,47,6, -12,-123,45,-24,31,-73,119,1,16,86,16,-44,-15,58,-95,-58,-15,61,-54,-16, 
  /* [12][0][][] */ -74,89,72,63,-27,38,56,44,-119,-51,-127,-36,-40,-12,2,42,4,-102,15,45, -31,62,67,24,-59,53,37,17,28,-34,-19,20,59,-65,79,17,-41,-34,-44,-65, -80,23,41,117,-83,99,57,23,-17,-54,6,-71,-72,-20,112,-109,-1,53,18,-120, 
  /* [13][0][][] */ 23,19,15,-11,39,35,48,-2,6,47,-8,-110,-29,17,60,105,-43,-26,-24,-39, -85,17,-64,-71,-66,-74,88,-38,0,45,-80,9,93,6,51,-21,77,-57,64,-14, -84,-23,57,-33,107,66,28,9,-24,-60,127,15,-29,-4,-30,117,-108,-43,-27,57, 
  /* [14][0][][] */ 92,0,-36,-54,-84,29,-55,32,86,-19,100,30,23,-47,-42,-127,-85,55,67,-43, -86,-5,100,32,-18,43,5,3,-44,26,-79,3,57,48,-51,36,26,62,104,-40, -33,-58,-81,15,72,-72,-47,-63,-28,-55,-105,-16,-49,-24,56,-31,46,94,-4,79, 
  /* [15][0][][] */ -41,26,29,39,-88,-12,-70,58,80,-6,36,-12,-5,99,127,-18,79,-57,12,-97, -15,-14,-5,61,26,-47,-42,-16,-78,-76,37,40,28,52,-29,-9,50,-26,64,-63, -50,-53,-28,-13,-3,-7,61,77,36,-3,64,31,48,18,60,44,25,-28,-49,7, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 16,1,3,20 } };
const TfArray<16, float> quant11_scale = { 16, { 0.0028231272008270025, 0.0039583072066307068, 0.0037579054478555918, 0.0034401316661387682, 0.0028636141214519739, 0.0036217705346643925, 0.0032572813797742128, 0.0039331503212451935, 0.0036825689021497965, 0.0040317610837519169, 0.0031896338332444429, 0.0028472908306866884, 0.0028722377028316259, 0.0031761243008077145, 0.0030487829353660345, 0.003258709330111742, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const TfArray<4, int> tensor_dimension12 = { 4, { 1,1,50,20 } };
const TfArray<4, int> tensor_dimension13 = { 4, { 1,1,50,16 } };
const TfArray<1, float> quant13_scale = { 1, { 0.034967381507158279, } };
const TfArray<1, int> quant13_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&quant13_zero, 0 };
const TfArray<4, int> tensor_dimension14 = { 4, { 1,50,1,16 } };
const TfArray<4, int> tensor_dimension15 = { 4, { 1,25,1,16 } };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,25,16 } };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,1,25,32 } };
const TfArray<1, float> quant17_scale = { 1, { 0.048063334077596664, } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&g0::quant13_zero, 0 };
const TfArray<4, int> tensor_dimension18 = { 4, { 1,25,1,32 } };
const TfArray<4, int> tensor_dimension19 = { 4, { 1,13,1,32 } };
const TfArray<2, int> tensor_dimension20 = { 2, { 1,416 } };
const TfArray<2, int> tensor_dimension21 = { 2, { 1,4 } };
const TfArray<1, float> quant21_scale = { 1, { 0.19133411347866058, } };
const TfArray<1, int> quant21_zero = { 1, { 14 } };
const TfLiteAffineQuantization quant21 = { (TfLiteFloatArray*)&quant21_scale, (TfLiteIntArray*)&quant21_zero, 0 };
const TfArray<1, float> quant22_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant22 = { (TfLiteFloatArray*)&quant22_scale, (TfLiteIntArray*)&g0::quant13_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 12 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 12,11,10 } };
const TfArray<1, int> outputs1 = { 1, { 13 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 13,2 } };
const TfArray<1, int> outputs2 = { 1, { 14 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 14 } };
const TfArray<1, int> outputs3 = { 1, { 15 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 15,3 } };
const TfArray<1, int> outputs4 = { 1, { 16 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 16,9,8 } };
const TfArray<1, int> outputs5 = { 1, { 17 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 17,4 } };
const TfArray<1, int> outputs6 = { 1, { 18 } };
const TfLitePoolParams opdata7 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs7 = { 1, { 18 } };
const TfArray<1, int> outputs7 = { 1, { 19 } };
const TfLiteReshapeParams opdata8 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs8 = { 2, { 19,5 } };
const TfArray<1, int> outputs8 = { 1, { 20 } };
const TfLiteFullyConnectedParams opdata9 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs9 = { 3, { 20,7,6 } };
const TfArray<1, int> outputs9 = { 1, { 21 } };
const TfLiteSoftmaxParams opdata10 = { 1 };
const TfArray<1, int> inputs10 = { 1, { 21 } };
const TfArray<1, int> outputs10 = { 1, { 22 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 1008), (TfLiteIntArray*)&g0::tensor_dimension0, 1000, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 1664, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 128, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 1536, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension12, 1000, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 1008), (TfLiteIntArray*)&g0::tensor_dimension13, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension14, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension15, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension17, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension19, 416, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension20, 416, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 416), (TfLiteIntArray*)&g0::tensor_dimension21, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension21, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 23, };
const size_t tflNodes_subgraph_index[] = {0, 11, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  22, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_968747_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 23;
  for (size_t i = 0; i < 23; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_968747_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_968747_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_968747_3_invoke() {
  for (size_t i = 0; i < 11; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_968747_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
